### ISSUE TITLE
Poblems with CSI extraction

### ISSUE THREAD

**Issue by douttaCzye** [nexmonster/nexmon_csi_bin#5]
Grateful for your excellent job!
I use the _Raspberry Pi 3B+_, with kernel _5.10.92_. Unfortunately I ran into the following issues while capturing CSI:

1. After executing the install scripts, when cursor on the wifi icon, it shows **'no wireless interface found'** is that normal?
2. I connect the raspi and laptop with an ethernet cable,  making laptop connected to the mobile hotspot, then I ran the command 
` mcp -C 1 -N 1 -c 36/80`
`ifconfig wlan0 up`
then ran `ip link show wlan0` to find the mon0'Mode is Down, which dont seems right
3. I ran the following command as instructed
`nexutil -Iwlan0 -s500 -b -l34 -vKuABEQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==`
`iw dev wlan0 interface add mon0 type monitor`
`ip link set mon0 up`
then ran `ip link show wlan0` to find the mon0'Mode is Down, which dont seems right either
4. I ran `tcpdump -i wlan0 dst port 5500 -vv -w output.pcap -c 1000` and got feedback **`Got 0`**

It'll be of great help if you would fix the issues above for me. Thx!
@zeroby0

**Comment by rafay0111** [comment]
How did you fix it?
@zeroby0
