### ISSUE TITLE
Install script not working

### ISSUE THREAD

**Issue by BrendanxP** [nexmonster/nexmon_csi_bin#6]
I used the recommended install that gives version `Linux raspberrypi 5.10.92-v7l+ #1514 SMP Mon Jan 17 17:38:03 GMT 2022 armv7l GNU/Linux` and I ran the install script. However, after running the install script and rebooting, I get an error trying to run the Nexmon CSI. 

`mcp -c 36/40 -C 1 -N 1`
Gives: JtgBEQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==

`sudo ifconfig wlan0 up`

The following command gives an error
`sudo nexutil -Iwlan0 -s500 -b -l34 -vJtgBEQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==`

The error is as follows:
`nex_init_netlink: socket error (93: Protocol not supported)
nex_init_netlink: socket error (93: Protocol not supported)
nex_init_netlink: bind error (9: Bad file descriptor)
nex_init_netlink: connect error (9: Bad file descriptor)
ERR (__nex_driver_netlink): no valid answer received`

It is the same error as mentioned [here](https://github.com/seemoo-lab/nexmon_csi/issues/258), however, the solution as proposed by @zeroby0 is to run the install script, which I am doing, with the Raspberry Pi OS version, which I am using.

If anyone can help me out that would be hugely appreciated!

**Comment by zeroby0** [comment]
The nexmon kernel module probably crashed. Restarting the Pi might fix it.

**Comment by BrendanxP** [comment]
Restarting multiple times fixed it. Restarting even twice still gave the issue.
